auth_enabled: false

server:
  http_listen_port: 3100

common:
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

ingester:
  wal:
    dir: /tmp/loki/wal

compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem

ruler:
  alertmanager_url: http://localhost:9093
