receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  loki:
    endpoint: ${LOKI_ENDPOINT}
  logging:
    loglevel: info

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, logging]
